/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TailorRouteImport } from './routes/tailor'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecoverAccountRouteImport } from './routes/recover-account'
import { Route as MatchmakerRouteImport } from './routes/matchmaker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FinalizeRouteImport } from './routes/finalize'
import { Route as CvRouteImport } from './routes/cv'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TailorIndexRouteImport } from './routes/tailor.index'
import { Route as TailorStrategyRouteImport } from './routes/tailor.strategy'
import { Route as TailorReadinessRouteImport } from './routes/tailor.readiness'
import { Route as TailorMatchRouteImport } from './routes/tailor.match'
import { Route as TailorExportRouteImport } from './routes/tailor.export'
import { Route as TailorCvRouteImport } from './routes/tailor.cv'
import { Route as TailorCoverLetterRouteImport } from './routes/tailor.cover-letter'
import { Route as MatchmakerJobSlugRouteImport } from './routes/matchmaker.$jobSlug'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorRoute = TailorRouteImport.update({
  id: '/tailor',
  path: '/tailor',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverAccountRoute = RecoverAccountRouteImport.update({
  id: '/recover-account',
  path: '/recover-account',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakerRoute = MatchmakerRouteImport.update({
  id: '/matchmaker',
  path: '/matchmaker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalizeRoute = FinalizeRouteImport.update({
  id: '/finalize',
  path: '/finalize',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorIndexRoute = TailorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TailorRoute,
} as any)
const TailorStrategyRoute = TailorStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => TailorRoute,
} as any)
const TailorReadinessRoute = TailorReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => TailorRoute,
} as any)
const TailorMatchRoute = TailorMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => TailorRoute,
} as any)
const TailorExportRoute = TailorExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => TailorRoute,
} as any)
const TailorCvRoute = TailorCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => TailorRoute,
} as any)
const TailorCoverLetterRoute = TailorCoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => TailorRoute,
} as any)
const MatchmakerJobSlugRoute = MatchmakerJobSlugRouteImport.update({
  id: '/$jobSlug',
  path: '/$jobSlug',
  getParentRoute: () => MatchmakerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/builder': typeof BuilderRoute
  '/cv': typeof CvRoute
  '/finalize': typeof FinalizeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/matchmaker': typeof MatchmakerRouteWithChildren
  '/recover-account': typeof RecoverAccountRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/tailor': typeof TailorRouteWithChildren
  '/verify': typeof VerifyRoute
  '/matchmaker/$jobSlug': typeof MatchmakerJobSlugRoute
  '/tailor/cover-letter': typeof TailorCoverLetterRoute
  '/tailor/cv': typeof TailorCvRoute
  '/tailor/export': typeof TailorExportRoute
  '/tailor/match': typeof TailorMatchRoute
  '/tailor/readiness': typeof TailorReadinessRoute
  '/tailor/strategy': typeof TailorStrategyRoute
  '/tailor/': typeof TailorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/builder': typeof BuilderRoute
  '/cv': typeof CvRoute
  '/finalize': typeof FinalizeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/matchmaker': typeof MatchmakerRouteWithChildren
  '/recover-account': typeof RecoverAccountRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/verify': typeof VerifyRoute
  '/matchmaker/$jobSlug': typeof MatchmakerJobSlugRoute
  '/tailor/cover-letter': typeof TailorCoverLetterRoute
  '/tailor/cv': typeof TailorCvRoute
  '/tailor/export': typeof TailorExportRoute
  '/tailor/match': typeof TailorMatchRoute
  '/tailor/readiness': typeof TailorReadinessRoute
  '/tailor/strategy': typeof TailorStrategyRoute
  '/tailor': typeof TailorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/builder': typeof BuilderRoute
  '/cv': typeof CvRoute
  '/finalize': typeof FinalizeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/matchmaker': typeof MatchmakerRouteWithChildren
  '/recover-account': typeof RecoverAccountRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/tailor': typeof TailorRouteWithChildren
  '/verify': typeof VerifyRoute
  '/matchmaker/$jobSlug': typeof MatchmakerJobSlugRoute
  '/tailor/cover-letter': typeof TailorCoverLetterRoute
  '/tailor/cv': typeof TailorCvRoute
  '/tailor/export': typeof TailorExportRoute
  '/tailor/match': typeof TailorMatchRoute
  '/tailor/readiness': typeof TailorReadinessRoute
  '/tailor/strategy': typeof TailorStrategyRoute
  '/tailor/': typeof TailorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/advisor'
    | '/analytics'
    | '/builder'
    | '/cv'
    | '/finalize'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/matchmaker'
    | '/recover-account'
    | '/register'
    | '/reset-password'
    | '/review'
    | '/tailor'
    | '/verify'
    | '/matchmaker/$jobSlug'
    | '/tailor/cover-letter'
    | '/tailor/cv'
    | '/tailor/export'
    | '/tailor/match'
    | '/tailor/readiness'
    | '/tailor/strategy'
    | '/tailor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/advisor'
    | '/analytics'
    | '/builder'
    | '/cv'
    | '/finalize'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/matchmaker'
    | '/recover-account'
    | '/register'
    | '/reset-password'
    | '/review'
    | '/verify'
    | '/matchmaker/$jobSlug'
    | '/tailor/cover-letter'
    | '/tailor/cv'
    | '/tailor/export'
    | '/tailor/match'
    | '/tailor/readiness'
    | '/tailor/strategy'
    | '/tailor'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/advisor'
    | '/analytics'
    | '/builder'
    | '/cv'
    | '/finalize'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/matchmaker'
    | '/recover-account'
    | '/register'
    | '/reset-password'
    | '/review'
    | '/tailor'
    | '/verify'
    | '/matchmaker/$jobSlug'
    | '/tailor/cover-letter'
    | '/tailor/cv'
    | '/tailor/export'
    | '/tailor/match'
    | '/tailor/readiness'
    | '/tailor/strategy'
    | '/tailor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdvisorRoute: typeof AdvisorRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BuilderRoute: typeof BuilderRoute
  CvRoute: typeof CvRoute
  FinalizeRoute: typeof FinalizeRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  MatchmakerRoute: typeof MatchmakerRouteWithChildren
  RecoverAccountRoute: typeof RecoverAccountRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewRoute: typeof ReviewRoute
  TailorRoute: typeof TailorRouteWithChildren
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailor': {
      id: '/tailor'
      path: '/tailor'
      fullPath: '/tailor'
      preLoaderRoute: typeof TailorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-account': {
      id: '/recover-account'
      path: '/recover-account'
      fullPath: '/recover-account'
      preLoaderRoute: typeof RecoverAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaker': {
      id: '/matchmaker'
      path: '/matchmaker'
      fullPath: '/matchmaker'
      preLoaderRoute: typeof MatchmakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finalize': {
      id: '/finalize'
      path: '/finalize'
      fullPath: '/finalize'
      preLoaderRoute: typeof FinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailor/': {
      id: '/tailor/'
      path: '/'
      fullPath: '/tailor/'
      preLoaderRoute: typeof TailorIndexRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/strategy': {
      id: '/tailor/strategy'
      path: '/strategy'
      fullPath: '/tailor/strategy'
      preLoaderRoute: typeof TailorStrategyRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/readiness': {
      id: '/tailor/readiness'
      path: '/readiness'
      fullPath: '/tailor/readiness'
      preLoaderRoute: typeof TailorReadinessRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/match': {
      id: '/tailor/match'
      path: '/match'
      fullPath: '/tailor/match'
      preLoaderRoute: typeof TailorMatchRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/export': {
      id: '/tailor/export'
      path: '/export'
      fullPath: '/tailor/export'
      preLoaderRoute: typeof TailorExportRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/cv': {
      id: '/tailor/cv'
      path: '/cv'
      fullPath: '/tailor/cv'
      preLoaderRoute: typeof TailorCvRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/cover-letter': {
      id: '/tailor/cover-letter'
      path: '/cover-letter'
      fullPath: '/tailor/cover-letter'
      preLoaderRoute: typeof TailorCoverLetterRouteImport
      parentRoute: typeof TailorRoute
    }
    '/matchmaker/$jobSlug': {
      id: '/matchmaker/$jobSlug'
      path: '/$jobSlug'
      fullPath: '/matchmaker/$jobSlug'
      preLoaderRoute: typeof MatchmakerJobSlugRouteImport
      parentRoute: typeof MatchmakerRoute
    }
  }
}

interface MatchmakerRouteChildren {
  MatchmakerJobSlugRoute: typeof MatchmakerJobSlugRoute
}

const MatchmakerRouteChildren: MatchmakerRouteChildren = {
  MatchmakerJobSlugRoute: MatchmakerJobSlugRoute,
}

const MatchmakerRouteWithChildren = MatchmakerRoute._addFileChildren(
  MatchmakerRouteChildren,
)

interface TailorRouteChildren {
  TailorCoverLetterRoute: typeof TailorCoverLetterRoute
  TailorCvRoute: typeof TailorCvRoute
  TailorExportRoute: typeof TailorExportRoute
  TailorMatchRoute: typeof TailorMatchRoute
  TailorReadinessRoute: typeof TailorReadinessRoute
  TailorStrategyRoute: typeof TailorStrategyRoute
  TailorIndexRoute: typeof TailorIndexRoute
}

const TailorRouteChildren: TailorRouteChildren = {
  TailorCoverLetterRoute: TailorCoverLetterRoute,
  TailorCvRoute: TailorCvRoute,
  TailorExportRoute: TailorExportRoute,
  TailorMatchRoute: TailorMatchRoute,
  TailorReadinessRoute: TailorReadinessRoute,
  TailorStrategyRoute: TailorStrategyRoute,
  TailorIndexRoute: TailorIndexRoute,
}

const TailorRouteWithChildren =
  TailorRoute._addFileChildren(TailorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdvisorRoute: AdvisorRoute,
  AnalyticsRoute: AnalyticsRoute,
  BuilderRoute: BuilderRoute,
  CvRoute: CvRoute,
  FinalizeRoute: FinalizeRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  MatchmakerRoute: MatchmakerRouteWithChildren,
  RecoverAccountRoute: RecoverAccountRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewRoute: ReviewRoute,
  TailorRoute: TailorRouteWithChildren,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
